Create hover effect for links
mohametalmeari/mohametalmeari.github.io pull request #3
Opened 2023-03-23 18:02 UTC by mohametalmeari

2023-03-23 20:02 UTC, topeogunleye requested changes
Hi @mohametalmeari, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Try-Again](https://user-images.githubusercontent.com/52934128/180646051-aed7efa6-6d15-4853-9962-73186e366f2c.gif)

> ## (Highlights) Good Points: 💪 
> * Good commit messages. :heavy_check_mark:
> * No linter errors. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:
> * Professional README file. :heavy_check_mark:

## Required Changes ♻️
_Check the comments under the review._
- [x] I kindly suggest that you surround your logo on line 16 with an `a` tag. 

>https://github.com/mohametalmeari/Portfolio/blob/17ab35fd1d37409749889b6b06ff743408e72618/index.html#L16

---


- [ ] I kindly suggest that your hamburger menu has a `nav` tag.

>https://github.com/mohametalmeari/Portfolio/blob/17ab35fd1d37409749889b6b06ff743408e72618/index.html#L17

---

- [x]  Please note that the main title `I'm Mohamad. Glad to see you!` should be an `<h1>`. this will enhance your website's [SEO ](https://mailchimp.com/marketing-glossary/seo/)credit , so kindly fix that
>https://github.com/mohametalmeari/Portfolio/blob/17ab35fd1d37409749889b6b06ff743408e72618/index.html#L20
---
> * [x]  kindly update your code to make it more semantic and for the best HTML practices : the social icons should be listed inside a list `<ul> & <li>` instead of normal divs.

>https://github.com/mohametalmeari/Portfolio/blob/17ab35fd1d37409749889b6b06ff743408e72618/index.html#L28-L33

## See Example:
> 
> ```
> <ul class='...'>
> <li class='...'><a href='...' ><svg>...</svg></a></li>
> <li class='...'><a href='...' ><svg>...</svg></a></li>
> ...
> <li class='...'><a href='...' ><svg>...</svg></a></li>
> </ul>
> ```

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Nothing to mention

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 20:02 UTC, topeogunleye commented on style.css
- [x] I kindly suggest that you ensure that this section has the proper background image. Kindly use `background-image`, not `imgs` because the background-image is for decorative purpose only.

<img width="253" alt="image" src="https://user-images.githubusercontent.com/52934128/227337161-b9af1d3f-687f-4f17-91f2-325edd6890ba.png">

- [x] Please kindly find below a video of how to download your background image from the Figma [template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39-122&t=LsINqDyUeCKk04UF-0):

https://www.loom.com/share/2a9349ac8cfd4d67b12b4d490bc309f3

2023-03-23 21:00 UTC, mohametalmeari commented on style.css
Thank you @topeogunleye, I did all changes, but what do you mean by "hamburger menu has a nav tag", do you mean I put the hamburger menu inside a nav tag?

2023-03-24 04:34 UTC, topeogunleye commented on style.css
> Thank you @topeogunleye, I did all changes, but what do you mean by "hamburger menu has a nav tag", do you mean I put the hamburger menu inside a nav tag?

@mohametalmeari Yes, that'll work. Sorry for taking so long to reply back.

2023-03-24 07:51 UTC, amejid approved these changes
Hi @mohametalmeari, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
- Linter checks passing :heavy_check_mark: 
- Correct use of Github flow :heavy_check_mark: 
- Good UI design :heavy_check_mark: 
- Good semantic structure :heavy_check_mark: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 08:01 UTC, merged

2023-03-24 08:02 UTC, mohametalmeari commented
ToolBar and HeadLine are ready.